Vagrant.require_version ">= 1.7.2"


$script = <<PULL_SCRIPT

# download "docker-mirror" tool
curl   -o   /usr/local/bin/docker-mirror  https://raw.githubusercontent.com/William-Yeh/docker-host-tools/master/docker-mirror
chmod  a+x  /usr/local/bin/*

# pull images from Docker Hub
PRIVATE_DOCKER_REGISTRY=registry.com  docker-mirror  /vagrant/IMAGE-LIST


PULL_SCRIPT



Vagrant.configure(2) do |config|

    config.vm.box = "williamyeh/insecure-registry"
    config.vm.box_version = ">= 1.6.2"

    # avoid possible request "vagrant@127.0.0.1's password:" when "up" and "ssh"
    config.ssh.password = "vagrant"


    config.vm.provision "hosts" do |hosts|
        hosts.add_host '127.0.0.1', ['registry.com']
    end

    config.vm.provision "shell", inline: $script
    config.vm.provision "shell", path: "cleanup.sh"

end
