Vagrant.configure(2) do |config|

  config.vm.box = "williamyeh/ubuntu-trusty64-docker"

  #config.vm.box = "ubuntu/trusty64"
  #config.vm.box = "ubuntu/precise64"
  #config.vm.box = "bento/centos-7.1"
  #config.vm.box = "bento/centos-6.7"
  #config.vm.box = "debian/jessie64"
  #config.vm.box = "yungsang/coreos"
  #config.vm.box = "yungsang/coreos-alpha"
  #config.vm.box = "yungsang/coreos-beta"

end
