Vagrant.configure(2) do |config|

  config.vm.box = "williamyeh/ubuntu-trusty64-docker"

  #config.vm.box = "ubuntu/trusty64"
  #config.vm.box = "ubuntu/precise64"
  #config.vm.box = "chef/centos-7.0"
  #config.vm.box = "chef/centos-6.6"
  #config.vm.box = "chef/debian-7.6"
  #config.vm.box = "yungsang/coreos"
  #config.vm.box = "yungsang/coreos-alpha"
  #config.vm.box = "yungsang/coreos-beta"

end
